[package]
name = "goblin-signing"
license = "MIT"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/RaitoBezarius/goblin-signing"

[dependencies]
digest = "0.10.6"
# waiting for a release of goblin
goblin = { version = "0.6.0", git = "https://github.com/m4b/goblin.git", branch = "master" }
