[package]
name = "goblin-signing"
license = "MIT"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/RaitoBezarius/goblin-signing"

[dependencies]
digest = "0.10.6"
# waiting for a release of goblin
goblin = { git = "https://github.com/RaitoBezarius/goblin.git", branch = "write-certs" }
cms = { git = "https://github.com/RustCrypto/formats" }
der = { git = "https://github.com/RustCrypto/formats" }
x509-cert = { git = "https://github.com/RustCrypto/formats" }

[[example]]
name = "sign_binary"
